/* empty css                      */import{S as p,N as h,A as g}from"./assets/vendor-D7M8BDcB.js";(function(){const n=document.createElement("link").relList;if(n&&n.supports&&n.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))d(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const a of t.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&d(a)}).observe(document,{childList:!0,subtree:!0});function l(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function d(e){if(e.ep)return;e.ep=!0;const t=l(e);fetch(e.href,t)}})();let m=null;function w(){m||(m=new p(".gallery-swiper",{modules:[h,g],slidesPerView:1.2,spaceBetween:16,loop:!1,autoplay:{delay:2500,disableOnInteraction:!1},navigation:{nextEl:".gallery-next",prevEl:".gallery-prev"},breakpoints:{1440:{slidesPerView:"auto",spaceBetween:24}}}))}w();document.querySelectorAll(".faq-acc-el-trigger").forEach(c=>{c.addEventListener("click",()=>{const n=c.closest(".faq-acc-el"),l=n.querySelector(".faq-acc-el-descr-frame");n.classList.contains("open")?(n.classList.remove("open"),l.style.maxHeight="0"):(n.classList.add("open"),l.style.maxHeight=l.scrollHeight+"px")})});document.addEventListener("DOMContentLoaded",()=>{const c=document.querySelector(".menu-button"),n=c.querySelector(".icon"),l=document.querySelector(".modal"),d=document.querySelectorAll(".menu-list-item"),e=document.querySelector(".header");let t=!1;const a=`
<svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
  <rect x="0.5" y="0.5" width="23" height="23" rx="11.5" stroke="#D7BDF9" />
  <path d="M5 7H19M5 17H19M5 12H19" stroke="#444443" stroke-linecap="round" />
</svg>
    `,o=`
<svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
  <rect x="0.5" y="0.5" width="23" height="23" rx="11.5" stroke="#D7BDF9" />
  <path d="M6 6L11.75 11.75M11.75 11.75L6 17.5M11.75 11.75L17.5 17.5M11.75 11.75L17.5 6" stroke="#444443" stroke-linecap="round" stroke-linejoin="round" />
</svg>
    `;c.addEventListener("click",()=>{t=!t,n.innerHTML=t?o:a,t?r():s()}),d.forEach(u=>u.addEventListener("click",()=>{s(),n.innerHTML=a,t=!1})),window.addEventListener("scroll",i);function r(){l.style.display="block"}function s(){l.style.display="none"}function i(){e&&(window.scrollY>60?e.classList.add("header-scroll"):e.classList.remove("header-scroll"))}});document.addEventListener("DOMContentLoaded",()=>{function c(){const o=document.getElementById("site-header");return o?o.offsetHeight:0}function n(o){const r=document.getElementById(o);if(!r)return;const s=c(),i=r.getBoundingClientRect().top+window.pageYOffset-s;window.scrollTo({top:i,behavior:"smooth"})}document.querySelectorAll(".navigation-item a").forEach(o=>{o.addEventListener("click",function(r){const s=this.getAttribute("href");if(!s)return;const[i,u]=s.split("#");if(!u)return;const f=window.location.pathname.split("/").pop();!(i===""||i==="./"||i===f||i==="./"+f)||!document.getElementById(u)||(r.preventDefault(),n(u),t(u))})});const d=document.querySelectorAll("section[id]"),e=document.querySelectorAll(".navigation-item");function t(o){e.forEach(s=>s.classList.remove("active"));const r=document.querySelector(`.navigation-item a[href*="#${o}"]`);r&&r.closest(".navigation-item").classList.add("active")}function a(){const o=window.pageYOffset+c()+100;d.forEach(r=>{const s=r.offsetTop,i=s+r.offsetHeight;o>=s&&o<i&&t(r.id)})}if(window.addEventListener("scroll",a),window.location.hash){const o=window.location.hash.substring(1);setTimeout(()=>{n(o),t(o)},300)}});
//# sourceMappingURL=index.js.map
